### PR TITLE
fix: use relative paths when updating cache from Cloud Storage

### LINKED ISSUE #19: bucketrepo does not work well with GCS
Everytime my bucketrepo pod restarts, I get an empty index.yaml

I am seeing this error in my logs:

```
{"timestamp":"2020-02-06T14:10:51Z","serviceContext":{"service":"bucketrepo","version":"1.0"},"message":"failed to update cache for /tmp/bucketrepo/charts/index.yaml: reading file from cloud storage: blob (key \"tmp/bucketrepo/charts/index.yaml\") (code=NotFound): storage: object doesn't exist","severity":"ERROR","context":{"reportLocation":{"filePath":"internal/controller.go","lineNumber":295,"functionName":"(*FileController).chartReindex"}}}
```

It appears that bucketrepo is using the "cache.BaseDir" prefix in the cloud path as well. Whereas while updating the chart it uses the path without "cache.BaseDir".

As a temporary fix, I created a gs://repos/tmp/bucketrepo/charts/index.yaml with the expected contents manually, which results in bucket repo happily working with it, and updating the gs://repos/charts/index.yaml.

I am taking a copy of gs://repos/charts/index.yaml and pasting it to gs://repos/tmp/bucketrepo/charts/index.yaml every few days for now.

### PR DESCRIPTION
**Pull request by mateuszpodraza**
Fixes #19

### CODE REVIEW

**Comment by patrickleet** [comment]
Setting `config.cache.dir` to `./` also does this

```
config:
  cache:
    dir: ./
```

**Comment by patrickleet** [comment]
I've had bucketrepo delete all of my charts for not setting this enough times that I'm a bit afraid of this PR

**Comment by mateuszpodraza** [comment]
@patrickleet 
Setting the cache base for to `./`, works but it's a workaround - bucketrepo explicitly ignores it while uploading the index after reindexing, but includes it while downloading it.
That's what this PR fixes.

I've tested this locally and it seemed to work but once this PR gets merged, I can let you know on Slack what this did to my charts.

You can also backup your index.yaml from cloud storage before upgrading

**Comment by patrickleet** [comment]
> Setting the cache base to ./ works
not anymore - #42

**Comment by mateuszpodraza** [comment]
/hold
I don't want to merge this until we either separate charts for v2 and v3 of jx, or have better tests in this repo

**Comment by mateuszpodraza** [comment]
There's no point in keeping this PR open as it is, let's revisit the topic someday in the future.
/close

**Pull request closed without merging**
